name: Tidy
description: CLI package manager and template for Android. Inspired by slidy.
version: 0.0.1
homepage: https://https://github.com/theolm/Tidy

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  ansicolor: ^1.0.2
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0

executables:
  tidy: main
